import { createHash } from "node:crypto";
import path from "node:path";

import { findRelevantPackageName } from "./findRelevantPackageName";
import { getPackageJson } from "./getPackageJson";

/**
 * Returns a unique temporary directory path based on a salt and the relevant package name.
 * The path is generated by hashing the relative temp directory, package name, and salt.
 * This ensures uniqueness and avoids collisions.
 * The resulting directory is located under the system's temp directory,
 * with the hash truncated to 8 characters for brevity.
 */
export async function getTempDir(salt: string): Promise<string> {
  const relevantPackageName = (await findRelevantPackageName()) ?? "";
  const packageJson = await getPackageJson();
  const hash = createHash("sha1")
    .update(packageJson.name)
    .update(packageJson.version)
    .update(relevantPackageName)
    .update(salt)
    .digest("hex")
    .slice(0, 8);

  // Bun's static server doesn't handle bundling from a temp directory well,
  // or any directory outside the project root, for that matter.
  // So we use a directory inside the current working directory
  // instead of the system's temp directory.
  //
  // TODO: Uncomment this when Bun supports bundling from directories
  // outside the project root.
  // const tempDirBase = path.resolve(os.tmpdir(), "knyt/glazier");
  const tempDirBase = path.resolve(process.cwd(), ".knyt/glazier");

  return path.resolve(tempDirBase, hash);
}
