import type { RouterTypes } from "bun";

import type {
  BunHTMLBundleModule,
  GlazierPluginOptions,
} from "../transform/mod";
import { GlazierServer } from "./GlazierServer";

/**
 * Returns a Bun route handler that serves HTML markup using the Knyt Glazier transformer.
 *
 * @param htmlModulePromise - Promise resolving to a Bun HTML bundle module.
 * @param options - Optional Glazier plugin configuration. If omitted, it reuses the configuration from the default plugin instance.
 *
 * @remarks
 *
 * This function is intended for use with Bun's server to deliver dynamic HTML markup
 * generated by Knyt views, components, and server-side includes.
 *
 * To clarify, this function only serves markup; it doesn't bundle and serve an HTML file with its assets.
 *
 * @beta This API is experimental and may change.
 */
export function serveMarkup<RoutePath extends string = string>(
  htmlModulePromise: Promise<BunHTMLBundleModule>,
  options?: GlazierPluginOptions,
): RouterTypes.RouteHandler<RoutePath> {
  return new GlazierServer(htmlModulePromise, options).fetch;
}
