import { GlazierServer } from "./GlazierServer.ts";
import type { GlazierPluginOptions } from "../transform/mod.ts";
import type { RouteHandler } from "../types.ts";

/**
 * Returns a Bun route handler that serves HTML markup using the Knyt Glazier transformer.
 *
 * @param input - Promise resolving to a Bun HTML bundle module.
 * @param options - Optional Glazier plugin configuration. If omitted, it reuses the configuration from the default plugin instance.
 *
 * @remarks
 *
 * This function is intended for use with Bun's server to deliver dynamic HTML markup
 * generated by Knyt views, components, and server-side includes.
 *
 * To clarify, this function only serves markup; it doesn't bundle and serve an HTML file with its assets.
 *
 * @beta This API is experimental and may change.
 */
export function serveMarkup<RoutePath extends string = string>(
  input: GlazierServer.Input,
  options?: GlazierPluginOptions,
): RouteHandler<RoutePath> {
  return new GlazierServer(input, options).fetch;
}
